default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: reading_scores
  host: localhost

test:
  <<: *default
  database: reading_scores_test
  host: localhost
